name: Release

on:
  release:
    types: [created]

env:
  NODE_VERSION: '18'

jobs:
  publish:
    name: Build and Publish to NPM
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Run linting
      run: npm run lint

    - name: Run type checking
      run: npm run typecheck

    - name: Build package
      run: npm run build

    - name: Update package version
      run: |
        # Extract version from release tag (remove 'v' prefix if present)
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "Setting version to: $VERSION"
        
        # Check if version needs to be updated
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        if [ "$VERSION" != "$CURRENT_VERSION" ]; then
          npm version $VERSION --no-git-tag-version
          echo "Version updated to: $VERSION"
        else
          echo "Version already matches release tag: $VERSION"
        fi

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}